### ISSUE TITLE
Compatability issue: With Nameless Servers

### ISSUE THREAD

**Issue by Timongcraft** [Zolo101/NotEnoughServers#1]
With the current version of the mod and if you use the "Nameless Servers" Mod you can#t use the /joinserver command because the servers have no names maybe you could in that case display the ips or add anther field to the "Edit Server Menu" where you can set a name for this mod.

Nameless Servers Mod: https://modrinth.com/mod/nameless-servers

**Comment by Zolo101** [comment]
I'll look into a fix over the weekend, thank you for letting me know! It'll probably just be having the name as the IP like you said.

**Comment by Zolo101** [comment]
Fix will be in v1.1.1 for 1.19.x 😎

**Comment by Timongcraft** [comment]
Ok, thanks
