### ISSUE TITLE
Correctly set minecraft version requirement

### ISSUE THREAD

**Issue by Timongcraft** [Zolo101/NotEnoughServers#2]
In you fix: https://github.com/Zolo101/NotEnoughServers/commit/a4e73748893227f14752b6bacb90f3071c582dbe#diff-882c6606823cf6c4e4114c1125850a04ed3180c48aef0e1467f1e4022b235db2 you changed the minecraft version from
"1.19.x" -> ">=1.19.x" but it has to be ">=1.19" if it should work for 1.19 and higher.

**Comment by Timongcraft** [comment]
Pull request #3

**Comment by Zolo101** [comment]
Thank you for the PR! I've replaced the v1.1.1 build on Modrinth & Curseforge with this working version

**Comment by Timongcraft** [comment]
No problem, thanks for creating the mod
