### ISSUE TITLE
Pressing R or A also types those keys into the server name field

### ISSUE THREAD

**Issue by BetaKors** [Zolo101/NotEnoughServers#4]
Pressing R or A doesn't only open the "Add Server" or "Edit" menus, they also add those keys into the server field. So pressing A, for example, opens the "Add Server" menu with the server name field being "Minecraft Servera" instead of "Minecraft Server". The same happens when trying to edit a server, so pressing R to edit a server called "Example" opens the "Edit" menu with the server name field being "Exampler".

**Comment by BetaKors** [comment]
Might also be relevant to say that I'm on the 1.19.3 version.

**Comment by BetaKors** [comment]
Oops, closed this issue on accident.

**Comment by Zolo101** [comment]
Happens in:

- 1.19.3 (1.1.0 and 1.1.1)
- 1.19 - 1.19.2 (1.1.0)

**Comment by Zolo101** [comment]
I was able to fix this by hacking in a timer that defocuses (blurs) the text input for a extremely short (1ms) amount of time when you enter the add/rename server screen. I'm not that experienced with how minecraft handles keys so there's probably a way better way to fix it...

This fix will be in 2.0.0+ (so 1.21+ for now)

**Comment by BetaKors** [comment]
I don't think it's that hacky — us front-enders have to do this on the web all the time; since whenever you change something in the DOM and want to get some data (like, if you want to change the size of an element and then get its bounding box) you have to wait for it to update, and the easiest to do that is to just use `setTimeout` to wait for a little tiny bit for the DOM to update.

Although, in this case, isn't there a way to cancel key press events? I haven't read the source to understand how exactly you're listening to those key presses but there might be a way to just cancel them before the input field even has time to listen for those same key presses.
